### ISSUE TITLE
Command-line quick start

### ISSUE THREAD

**Issue by alptugan** [ipfs/ipfs-docs#1106]
hello there,
I am on MAC, Big Sur with Mid 2015 Macbook Pro
1) Using Desktop client
First, I installed desktop client.
Added some files for testing.
I could see the files on desktop app. But could not access them from browser -> https://ipfs.io/ipfs/<hash_link_of_the_file>

2) Using CLI (Terminal.app)
Installed ipfs through your documentation
Init the $ ipfs daemon successfully
Access to web-gui successfully
>ipfs add "path_to_my_file" successfully
But the file did not show up neither on web-gui or on ipfs server (https://ipfs.io/ipfs/<hash_link_of_the_file>)

I don't get any errors, or any warning messages. Everything seems to work fine. 
But I could not add files to database

**Comment by TheDiscordian** [comment]
Hello @alptugan!

1. Sounds like a NAT configuration issue, there's a doc about this here: https://docs.ipfs.io/how-to/nat-configuration/

2. You added the file to your daemon, which by default *pins* it, but doesn't add it to your MFS. For the files tab on the webUI, that's looking at your MFS. If you perform `ipfs files cp /ipfs/<yourCIDhere> /name_of_file_incl_extension` it'll appear in your webUI as expected. There's more info about it [here](https://docs.ipfs.io/concepts/file-systems/#mutable-file-system-mfs) using JS as an example instead of CLI commands, but the commands are similar.

In the future, please ask support related questions on our forums or in [one of our chats](https://docs.ipfs.io/community/chat/)! We have a friendly community ready, willing, and able to answer these types of questions. Though if you're unable, feel free to reply to this issue with any additional information you might need. I'm closing it now, but you should still be able to reply :).
