### ISSUE TITLE
How to contribute Chinese documentation for IPFS ? 

### ISSUE THREAD

**Issue by Rock-liyi** [ipfs/ipfs-docs#1164]
Hello  Everyone,
    I am LiYi ,  my english name is Rock, come from china ,i really appreciate everything the ipfs team did , you are awesome  and wonderful. 
   I have been a  programmer for seven years, i would like to   join   your team to  contribute my power .

   Firstly , i am going to translate  english docs  to chinese docs ,because  there are many people want to study IPFS  in china.

   Finaly,   can i  commit a PR  for this ?  Is  there anything that  I need  to pay attention to   or  where shoud i  start from here ?

**Comment by johnnymatthews** [comment]
Hi there, thanks for your interest in IPFS! While translations are super useful, manually translating the docs is a _huge_ effort. Because of this, we're looking at manual doc translations.

However, you're more than welcome to fork this repo and host your own version of the docs!

Again, thanks for your interest!
