### ISSUE TITLE
Automation should update versions without 'v' prefix

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#1186]
@laurentsenta seems that automation does not update occurrences without `v` prefix?  Will you have time to take a look?

Example:
- https://github.com/ipfs/ipfs-docs/pull/1174 replaced `v0.12.0` to `v0.13.0` but did not touch `0.12.0` 

This was noticed in https://github.com/ipfs/ipfs-docs/pull/1177 which applied the change manually, but we need automatic fix for the future.

**Comment by laurentsenta** [comment]
@lidel I double-checked the script, it works as expected,

It did replace `0.12.2` (the current version) by `0.13.0` (the new version) and left older versions (`0.12.0`) alone.

The bug comes from https://github.com/ipfs/ipfs-docs/pull/1121 we left a few `0.12.0`. I should have caught this during the review, sorry about that! Thanks to https://github.com/ipfs/ipfs-docs/pull/1177/files now everyone is on `0.13.0` and the next update will behave as expected.
