### ISSUE TITLE
Kubo RPC HTTP docs should skip "Required: no" 

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#1305]
> This bug was originally repoted by Brave – thx @cypt4!

https://docs.ipfs.tech/reference/kubo/rpc/ is generated from Kubo sources using code in https://github.com/ipfs/ipfs-docs/tree/main/tools/http-api-docs

RPC API was created for CLI: https://docs.ipfs.tech/reference/kubo/cli/ and  there is a concept  of "args" and "options" (optional args passed on cli via `--option`)

This is not universal, there are commands where we have mandatory "options", and it creates confusing docs like this:
 

![2022-10-11_00-20](https://user-images.githubusercontent.com/157609/194961411-d46b9e14-467a-4a49-836a-ab85101876fe.png)

## Proposed fix

I think easy fix here is to remove "Required: no" – it is just noise – and only have "Required: yes".

**Comment by ElPaisano** [comment]
If I'm understanding this issue correctly, the automated https://docs.ipfs.tech/reference/kubo/cli/ doc used to output a "Required: no" for a given entry. I say "used to" because the docs seem to have been updated a bunch since this issue was filed and a search of the page in question does not show any "Required: no" nor does it even look like the screenshot anymore. So, from what I can see, this issue has become irrelevant / resolved by other updates. 

Closing, please reopen or flag this if it is incorrect. Thanks
