### ISSUE TITLE
Hash collisions not mentioned

### ISSUE THREAD

**Issue by rmwiseman** [ipfs/ipfs-docs#1308]
Whilst I know it's very unlikely for the hash of two different pieces of content to be the same, it is possible, and so we have to assume it will happen at some point.  What happens then?  Is that handled by IPFS, and if so, how?

**Comment by bertrandfalguiere** [comment]
Theorically, a peer receiving either files matching the asked CID would accept it. 

Now, in practice, if you walk around the Earth, and each time you come back at your starting point you take one drop out of the ocean, and then keep walking until you completely empty the ocean one drop at a time, then put a sheet of paper on the ground, put all the water in the ocean and start all over again in order to put another sheet on top of the firstone,  and so on and so forth until the pile of paper touch the Sun, and propose a file for each step you took, the probability that you would have found a matching file someday in your almost eternal jouney is abysmally small. 

It should be fine.

**Comment by bertrandfalguiere** [comment]
(I heard this story for the number of ways to shuffle a deck of card, which is 52!, which is far smaller than 2^256)

**Comment by rmwiseman** [comment]
Love the analogy!  I hadn't realised the probability was quite as low as that!
