### ISSUE TITLE
Consolidate "Basic Concepts" into 1-2 page overview

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1433]
Currently, we have 8 pages under _Concepts_ > _Basic Concepts_. These pages existed before the recent content reorganization, and were just reshuffled. There has been discussion about how we might combine some of these pages into a similar, more concise _Basic Concepts_ section. The purpose of this issue is to discuss and settle on a refactor.

Assignee: @ElPaisano 

Epic: https://github.com/ipfs/ipfs-docs/issues/1432

Proposed Task:
- [ ] Read pages currently under _Basic Concepts_ and note the following: 
        - Duplicate content
        - Outdated content
        - Incorrect content
        - Missing content
        - Confusing  / misleading content
        - Broken links / links that should probably go somewhere else
        - Anything else that can be improved
- [ ] Create PR to rewrite basic concepts into 1-2 pages

**Comment by TMoMoreau** [comment]
I believe I had mentioned this already, but while it would be nice to have a one, maybe two, page consolidated version of these concepts, I would also like to see the full, uncondensed versions maintained in some way, for when users want to take a deeper dive into the topics.

(Also, I tagged this as "hard" because this is likely to require significant effort and understanding of the concepts, in order to create a sensible single page rundown of all of the important things.)
