### ISSUE TITLE
What is IPFS? Rewrite and make consistent in the docs.

### ISSUE THREAD

**Issue by TMoMoreau** [ipfs/ipfs-docs#1434]
Original issue here: #1368
Original comment bringing this issue to light: https://github.com/ipfs/ipfs-docs/pull/1363#discussion_r1047049575
Useful write-up on Notion by @2color about this topic: https://www.notion.so/What-is-IPFS-Definitions-02d37b91f6824bba8c246fdcd5021a5c

Opening a new issue for this, both to bring it back into priority and to expand the original scope. This issue will track all the pages that need to be updated, and will serve as a place of discussion around the topic.

There are a few pages in the docs that need to be rewritten to give a more accurate description and introduction to IPFS.

## Pages that need to be updated:
- [x] [The docs landing page](docs.ipfs.tech)
- [ ] ["What is IPFS?"](https://docs.ipfs.tech/concepts/what-is-ipfs/)
- [ ] ["How IPFS works](https://docs.ipfs.tech/concepts/how-ipfs-works/)
- Perhaps more(?)

**Comment by TMoMoreau** [comment]
Regarding the landing page: There's a line in the introduction that says, "Some call IPFS the hard drive for blockchain and Web3." I believe this is going to be removed, as I feel it only reinforces the misconception that IPFS is a storage solution. (And beyond that, may also reinforce the misconception that IPFS is/has a blockchain?)

**Comment by ElPaisano** [comment]
@TMoMoreau RE

> ## Pages that need to be updated:
> - [ ] [The docs landing page](docs.ipfs.tech)
> - [ ] ["What is IPFS?"](https://docs.ipfs.tech/concepts/what-is-ipfs/)
> - [ ] ["How IPFS works](https://docs.ipfs.tech/concepts/how-ipfs-works/)

The more I look into the basic concepts rewrite issue https://github.com/ipfs/ipfs-docs/issues/1433, the more I'm convinced it will involve some sort of rewrite / consolidation of "what is IPFS?" and "How IPFS works". So, I'd say it would be best to lump the definition updates work for those two pages into https://github.com/ipfs/ipfs-docs/issues/1433 since they're related.

As for the landing page, I think that's a great first sub-issue to tackle in this epic, and issue 1433 can be worked on at the same time and should address the definition work for "What is IPFS" and "How IPFS works"

I'll look around for other pages we might want to update

**Comment by TMoMoreau** [comment]
Makes sense to me. Only important thing is, if you plan on including rewritten definitions of IPFS in the concepts rewrite you have going, we just need to make sure it is consistent with the landing page definition I'm working on.

**Comment by ElPaisano** [comment]
> Makes sense to me. Only important thing is, if you plan on including rewritten definitions of IPFS in the concepts rewrite you have going, we just need to make sure it is consistent with the landing page definition I'm working on.

Good callout @TMoMoreau. Where can I find the PR link for the rewrite so I can take a look at that definition?
