### ISSUE TITLE
Add a "report abuse" resource to the docs somewhere

### ISSUE THREAD

**Issue by TMoMoreau** [ipfs/ipfs-docs#1458]
As discussed in this thread: https://filecoinproject.slack.com/archives/C04ENJL5S84/p1674748260526859

Currently, every now and then we'll get an issue opened in this repo reporting some kind of abuse of our CoC or ToS, and asking for instruction on what to do about it.
It would be useful to have a very visible resource regarding how to report abuse, and also link to the community code of conduct, this may also reduce the number of these issues that get opened in this repo.

We may also want to provide a link to these: https://discuss.ipfs.tech/tos and https://protocol.ai/legal/#terms-of-service

**Comment by ElPaisano** [comment]
@TMoMoreau possible way to do this would be to create one small PR for each of these tasks. Might also make sense to do one PR for Tasks 1 and 2 and one PR for 3 since it might require a little more investigation (see desription)

## Task 1

Add a note in two places regarding general contributions like Kubo does here https://github.com/ipfs/kubo#contributing 

For the moment, we could add a note with similar copy to the Kubo note and a link to https://github.com/ipfs/community/blob/master/code-of-conduct.md and then maybe similar copy to this sentence _Please contact [abuse@ipfs.io](mailto:abuse@ipfs.io) if you need to report a problem or address a grievance related to an abuse report_.

Suggested locations:
1. Add it (maybe as  `>`)  above the first line of https://github.com/ipfs/ipfs-docs#contribute-to-documentation
1. Add the note at the top of https://docs.ipfs.tech/community/contribute/ways-to-contribute/ (maybe a `:::warning` ?)

## Task 2

Add a note above the blurb in https://docs.ipfs.tech/community/#ipfs-forums that says something about how the forum follows this TOS https://discuss.ipfs.tech/tos

## Task 3

https://protocol.ai/legal/#terms-of-service looks like it's just in regards to general contents licensing / reuse / copy / etc.

Personally, I think that would make most sense under https://github.com/ipfs/ipfs-docs#license. However, I see we already have copy there

_All software code is copyright (c) Protocol Labs, Inc. under the MIT license. Other written documentation and content are copyright (c) Protocol Labs, Inc. under the [Creative Commons Attribution-Share-Alike License](https://creativecommons.org/licenses/by/4.0/)._

... so maybe not. I do think https://protocol.ai/legal/#terms-of-service is good to include somewhere, and this section would make most sense to me at the moment, but not sure how that relates to the other licenses mentioned

**Comment by 2color** [comment]
Dropping this here for visibility, since we might want to link to it: https://badbits.dwebops.pub/

**Comment by ElPaisano** [comment]
@TMoMoreau https://github.com/ipfs/ipfs-docs/pull/1473#issuecomment-1412830962 is able to address task 1 and 2 here I think

**Comment by ExTechOp** [comment]
This really does need some kind of a quick solution. I work with a CERT, and unfortunately a large part of account phishing these days arrives as either **ifps.dweb.link** or **ifps.io** links. A quick and easy-to find shutdown mechanism for these cases is sorely needed!

Here's a few examples of such phishing links, which are live as I write this (replace xx with tt, of course), the third one hides content behind Google translate:

- hxxps://bafybeibrwkihq4rstb6zuty2wco34agexgv7fay4ed5oxnkb5rkic3rc4a.ipfs.dweb.link/patauth.html?email@example.com+
- hxxps://ipfs.io/ipfs/QmNsWUYrzYBch6cp6kgjG3RUXjmS4R2RJUNLetUTVfkXcz?filename=OUWD%20KEN1%20OSHO%20MCZBR%20QDGPO%20RQWZ%20HMEFH.htm#email@example.com
- hxxps://2yo6v5qrw2dy56nsknoloethr7fopc4-ipfs-infura--ipfs-io.translate.goog/?_x_tr_hp=bafybeig2ziksmkhxbo2rcyzwquq&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&#email@example.com

**Comment by ExTechOp** [comment]
Also [commented on the operation of the abuse team](https://discuss.ipfs.tech/t/does-ipfs-have-an-abuse-team/15958), but of course my post with similar examples as above got hid by a spam filter.
