### ISSUE TITLE
Dynamic web elements that cannot be machine translated by chrome

### ISSUE THREAD

**Issue by lb-chc** [ipfs/ipfs-docs#1526]
Hi,I use chrome's web translation function to read your documentation, and there are some dynamic elements in it that cannot be translated by chrome (although this does not cause a real fatal dyslexia)

I have seen dynamic elements on other websites that can be translated by chrome, so can you change the dynamic elements in your documents to be translated by chrome? This will also save you the cost of internationalization

:-)

![Snipaste_2023-03-12_19-04-32](https://user-images.githubusercontent.com/69136546/224540749-ce97851f-fda5-444d-9e2c-b1fdeeda317a.png)

![Snipaste_2023-03-12_19-04-24](https://user-images.githubusercontent.com/69136546/224540745-e336c3b1-4d70-4c2a-a04d-47a9d16d6d17.png)

**Comment by ElPaisano** [comment]
@lb-chc thanks for taking the time to create an issue. This is good suggestion. However, due to a backlog of other tasks, further investigation into this has been deferred. However, we are noting this request, as we are planning on surveying the community about the documentation and what they would like to see, and you bring up a good point.

In the meantime, if you have a potential solution, feel free to make a PR to ipfs-docs. For now, I am going to close this issue. We can reopen at a later time if need be.
