### ISSUE TITLE
[DOCS ISSUE] Add abuse address to main page

### ISSUE THREAD

**Issue by ExTechOp** [ipfs/ipfs-docs#1541]
If you open `https://dweb.link/` you end up on the page `https://docs.ipfs.tech/how-to/address-ipfs-on-web/#further-resources` which has nothing obvious about reporting malware/phishing links. If you insist on effectively running a website anonymizer, at least make takedowns quick and easy, before malware protection software starts blocking access to all .dweb.iink links!

PS. Phishing: `hxxps://bafybeidkh4coovvqujg5s7yv4uuzzy2cogbkfvdfhpl2tcyexc2tqnywhu.ipfs.dweb.link/pxpstauth.html?email@example.com+`

**Comment by johnnymatthews** [comment]
Abuse information can be found here: https://ipfs.tech/help

**Comment by ExTechOp** [comment]
> Abuse information can be found here: https://ipfs.tech/help

The "landing page" address I gave above `https://docs.ipfs.tech/how-to/address-ipfs-on-web/#further-resources` does not have an obvious link leading there. The "search" on the top of the page only seems to search within this page. You really need a clear and direct "report abuse" link somewhere obvious, like on the left-hand address bar!

You have to remember that a much easier alternative to reporting these to you is (since both `//ipfs.io/` and `//...dweb.link/` just resolve to [209.94.90.1] and [2602:fea2:2::1]) we just block everything on the firewall level, and be done with scammers sending us phishing links via your anonymizer service.

**Comment by ElPaisano** [comment]
@ExTechOp the IPFS documentation also provides information on reporting abuse, scams, etc.

https://docs.ipfs.tech/community/

**Comment by ExTechOp** [comment]
The `dweb.link` "landing page" I mentioned above does not seem to provide the community link in any obvious way. Abuse reporting really needs to be immediately visible from both there and from the similar `ipfs.io` landing page.

Another issue is that unfortunately, the response time for abuse reports to the email address abuse@ipfs.io seems to be pretty bad. I have for example reported the address `https://bafybeiftuja6yhcuukmevumryl2nvy4fhgfx5wswvmuycx3vu7clz3rdp4.ipfs.dweb.link/#email@example.com` there already the first time on 2023-03-03 and also several times after that, but it still is operational. It'd be a lot easier to just block the service altogether, and many corporations will probably do so.

**Comment by johnnymatthews** [comment]
Taking a close look at this, you're right @ExTechOp. `https://docs.ipfs.tech/how-to/address-ipfs-on-web/#subdomain-gateway` doesn't give any indication about what to do about abuse. We _could_ add an abuse callout on this page, that'd direct people to the abuse@ipfs.io email.

However, I'm wondering if `https://docs.ipfs.tech/how-to/address-ipfs-on-web/#subdomain-gateway` is actually the best place to redirect people in the first place. It doesn't really make much sense. An _actual_ landing page would work way better.

Thanks for flagging this @ExTechOp. I can't speak to why emails to `abuse@ipfs.io` aren't getting addressed right away, but I'll see what's up.

I'm gonna keep this issue closed since it's more of an operations issue rather than a docs issue. But feel free to continue to add comments in here. A closed issue here just means we're not taking any direct _docs-related action_ to fix the problem. It doesn't mean we're going to ignore the problem entirely. We may open it back up if it turns out that we do want to add an `abuse@ipfs.io` callout.
