### ISSUE TITLE
Contenido en español

### ISSUE THREAD

**Issue by davespser** [ipfs/ipfs-docs#1604]
Por qué no hay tutoriales en castellano llevo un mes intentando entender ipfs pero falta contenido en mi idioma

**Comment by ElPaisano** [comment]
I understand your frustration and I wish I could provide you with resources. Unfortunately, we do not currently have the capacity to translate the documentation at this time. However, I will forward this information to the team so that they are aware of the community interest in Spanish-language documentation.  Thank you for taking the time to open an issue.
