### ISSUE TITLE
IPFS implementations missing notable impls

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-docs#1607]
I think some Implementations are missing here! Top of mind:
- IPVM from the Fission team - https://github.com/ipvm-wg
- WNFS? (is this an IPFS impl? I think so?) - https://github.com/wnfs-wg/
- RIBS by @magik6k - https://github.com/lotus-web3/ribs
- Durin
- Boxo

Others?

**Comment by BigLep** [comment]
@momack2 : ack - thanks.  We'll get this updated this week.

@ElPaisano : thanks for creating https://github.com/ipfs/ipfs-docs/pull/1609

**Comment by ElPaisano** [comment]
@momack2 thanks for opening. 

Sure thing @BigLep I've added in the requested updates in https://github.com/ipfs/ipfs-docs/pull/1609. Lumped it in with the changes requested by @hacdias in https://github.com/ipfs/ipfs-docs/issues/1606. Saw you added yourself as reviewer, LMK when it looks good and I'll merge

I was wondering if we might take the opportunity here to discuss automating this page so that we don't have to maintain by hand. I have some thoughts and would like to pick the engineers brains too. Not sure if this is the correct forum for that though.

**Comment by BigLep** [comment]
@ElPaisano - I responded in the PR.  

Concerning automating this page, feel free to share your thoughts.  That said, this is something that only gets touched a few times a year, so I don't think it yields much ROI to invest in automating.

@momack2 : I don't think IPVM and WNFS really fit as "implementations" from the definition at https://specs.ipfs.tech/architecture/principles/ .   They're not counter to the principles, but I think those projects need their own bucket, and I wasn't prepared to take on additional organizing of that page.  I'll bring this up at the [2023-06-01 Implementers working group](https://pl-strflt.notion.site/IPFS-Implementers-Sync-2023-06-01-52fbb1d6546e420699afb07f6396a619) to see if anyone has ideas.

**Comment by momack2** [comment]
thanks so much for making updates, @ElPaisano! 

@BigLep afaik at least IPVM (or their implementation Homestar - https://github.com/ipvm-wg/homestar/) meets the "musts" here: 
- must support addressability using CIDs.
- must expose operations (eg. retrieval, provision, indexing) on resources using CIDs. The operations that an implementation may support is an open-ended set, but this requirement should cover any interaction which the implementation exposes to other IPFS implementations.
- must verify that the CIDs it resolves match the resources they address, at least when it has access to the resources' bytes. Implementations may relax this requirement in controlled environments in which it is possible to ascertain that verification has happened elsewhere in a trusted part of the system.

Or what do you think it's missing?

**Comment by BigLep** [comment]
@momack2 : concerning IPVM, I was more resisting based on:
1. linking to the IPVM project/spec rather than implementation of it.  I see the value of surfacing homestar.  I added it here: https://github.com/ipfs/ipfs-docs/pull/1612
2. general fuzziness in my head of calling a "Wasm interpreter that acts as a distributed execution engine, scheduler, service discovery layer / matchmaking, and memoization system" (my understanding of IPVM) an IPFS implementation.  This stems from my own lack of knowledge here.

Anyways, I think we're good here now.  Thanks for kickstarting.
