### ISSUE TITLE
[CONTENT REQUEST] (Install IPFS Kubo doesn't work on windows 11!)

### ISSUE THREAD

**Issue by idoine** [ipfs/ipfs-docs#1640]
https://docs.ipfs.tech/install/command-line/#install-official-binary-distributions

![image](https://github.com/ipfs/ipfs-docs/assets/12686905/827c7d20-1af5-4f2d-b12d-9ed6fd205461)

![image](https://github.com/ipfs/ipfs-docs/assets/12686905/9098257f-b1d0-40e4-8c76-4a930e6ddfcc)

Because windows 11 "about_Execution_Policies" (https://go.microsoft.com/fwlink/?LinkID=135170.), `& $profile` don't work.

Use `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser` before, and it's well.

Then reset Policy to default with `Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser `

**Comment by ElPaisano** [comment]
Thank you for taking the time to create an issue. We will provide an update shortly.

**Comment by ElPaisano** [comment]
Hello @idoine could you please provide the following information?

1. Which version of Kubo binary are you trying to install? I assume latest, but want to be sure.
1.  Could you provide additional information on your system? OS is Windows 11, etc.?
1. Could you please clarify "Because windows 11 "about_Execution_Policies" (https://go.microsoft.com/fwlink/?LinkID=135170.), & $profile don't work."? I'm unclear on what is being said.

Thank you

**Comment by lidel** [comment]
Triage notes:
- The error is due to powershell  being disabled on user's system (the terminal works, but many functions are not available).

@idoine  the fix is to re-enable Powershell on your system, or use different instalaltion method (e.g. https://dist.ipfs.tech/#kubo)
