### ISSUE TITLE
Explain the relationship between MFS, IPFS, and UnixFS.

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-docs#297]
Tracking a user request at https://github.com/ipfs/go-ipfs/issues/7084#issuecomment-608552812

**URL of the page in question:**

Maybe: https://docs.ipfs.io/guides/concepts/mfs/

**What's wrong with this page?**

See confusion in above thread.

Related: how to manually create and modify unixfs directories (it has come up several times in the last week).

**Comment by johnnymatthews** [comment]
@hsanjuan do you still have the bandwidth to write this doc, or should I open it up for a bounty?

**Comment by realChainLife** [comment]
@hsanjuan does the update MFS document explain this issue better, the distinction between MFS & UnixFS?

**Comment by hsanjuan** [comment]
@johnnymatthews there has been a big update to this file (c5ed3ecc1e4d46b0e59a9c0718b239d3d432cca4). It has added examples using javascript (which I'm not sure are helpful at all as I would expect go's CLI examples). It still fails to explain how anything works in regards to MFS, while it does a better job with UnixFS.

If I were to work on this, I'd throw most of the MFS subsection away, keeping some small CLI example or two at the end for the usual workflow.

**Comment by johnnymatthews** [comment]
Correct, c5ed3ec was a bounty project completed by @realChainLife (in this thread). Using Go-IPFS or JS-IPFS is a debate for another time, but having any examples at all is a good thing. I'm assuming you no longer have time to write the changes you'd prefer to see on the page. Would you be able give list a few bullet points for what you'd like to see though?

**Comment by alexmmueller** [comment]
@johnnymatthews I could try to complete this issue if this makes sense?

**Comment by johnnymatthews** [comment]
Assigned to you @alexmmueller! Drop any questions you've got in here.

**Comment by johnnymatthews** [comment]
Are you still working on this one @alexmmueller?

**Comment by hiaux0** [comment]
Re: Current docs about ["File systems and IPFS"](https://docs.ipfs.io/concepts/ipfs-gateway/#overview): MFS and UnixFS

My profile: Someone new to web3 and IPFs

#### Path to understanding
The docs are doing a good job of explaining MFS and UnixFS respectively.
I got a vague understanding, that MFS is the "file sytem", that uses the "format" UnixFS.     _[U1]_

However, there was still this uncertain feeling of my understanding _[U1]_ being actually correct, due to these 2 passages in the docs:
(Both describe how they handle linking for me)

MFS: 
https://docs.ipfs.io/concepts/file-systems/#mutable-file-system-mfs
> MFS files and have all the work of **updating links** and hashes taken care of for you.

UnixFS: 
https://docs.ipfs.io/concepts/file-systems/#unix-file-system-unixfs
> [...] so it needs **metadata to link** all its blocks together. UnixFS is a protocol-buffers (opens new window)-based format [...]

Suddenly I wondered: "If both handle linking, are they actually both describing a "file system, thus are they alternatives?"
(yes, I'm aware, that the definition of UnixFS say it is a _format_, but the "FS" in its name didn't help to make this separation clear)

#### Wish to reduce confusion
It would have been helpful for me, to make this "hierarchy" between MFS and UnixFS clearer with a simple diagram, like

#251
```
     +---------+
     |   MFS   |   File system.
     +---------+
     |  UnixFS |   Files and directories.
     +---------+
     |   DAG   |   Nodes.
     +---------+
     |  Block  |   Stream of bits.
     +---------+
```

or a sentence like

https://github.com/ipfs/go-ipfs/issues/5051#issuecomment-393453908
> [...] Unixfs is a format. Mfs is the virtual filesystem tree, and the files api is an api interface that gives you filesystem operations over unixfs files/directories backed by mfs.
