### ISSUE TITLE
Clarify the differences between all the file APIs.

### ISSUE THREAD

**Issue by dadepo** [ipfs/ipfs-docs#301]
## [This issue has a bounty of $250](https://github.com/ipfs/devgrants/projects/1)

Is there an item missing from IPFS documentation that would be helpful to you? Please use this template to let us know!

**What's the subject of the item you're requesting?**

Do not know about the title, but it should be something that conveys that there are different files API, it could be confusing, and this is how to make sense out of them.

**What's the content of the item you're requesting?**

I think the quickest way to get a background information that led to me opening this issue can be found in this discussion on the forum: https://discuss.ipfs.io/t/why-is-ipfs-files-ls-being-deprecated/7881

**What will the user know how to do after going through this item?**

There are commands that appear across `ipfs`, `ipfs file`, and `ipfs files` command. eg: `ipfs ls`, `ipfs file ls`, and `ipfs files ls`. This could be quite confusing as it seems it touches on concepts that overlaps with Unixfs, MFS, and general IPFS. The aim of this content should be to help disambiguate all these seemingly overlapping concepts thereby providing clarify to readers on what each means.

**Would you be interested in helping create this item?**
Unfortunately for this one, I will have to say No, as I do not even know the correct information to put. Someone more familiar with the project would be the best for this.

**Is there any other feedback you'd like to share about IPFS docs?**

**Comment by ChaituVR** [comment]
I am thinking to work on this but still waiting for #518 to be merged

**Comment by johnnymatthews** [comment]
@ChaituVR I've assigned you to this issue. If you have any questions, just drop them in here :)

**Comment by Stebalien** [comment]
I'm a bit unclear on why we need to clarify that `ipfs ls` won't list files in MFS. Introducing `ipfs files ls` from the `ipfs ls` command seems like it may just confuse new users by introducing a new unfamiliar concept.

**Comment by ChaituVR** [comment]
@dadepo @johnnymatthews 

ipfs/go-ipfs#7755 Have all the tasks above, except `Explain that ipfs ls works on IPFS paths`
which is ignored because it may cause confusion to new users as mentioned by @Stebalien 

if we add "it only works with IPFS paths" - new users may feel "what other paths are available than IPFS? "
if we add "It won't work with MFS paths" - new users may feel "what is MFS?" 

For MFS users we are now mentioning that it works with ipfs files ls
`ipfs files ls works on both IPFS paths and MFS paths.`

If there is something you can suggest it would be helpfull
