### ISSUE TITLE
Remove the section regarding the Catalonian independence movement.

### ISSUE THREAD

**Issue by felizycontento** [ipfs/ipfs-docs#432]
The spanish governement did not close the sites related to the independence of Catalonia.

It just closed sites created to manage terrorism organizations and acts promoting it.

Thanks

**Comment by johnnymatthews** [comment]
Hi @felizycontento. Sorry for the delay is responding to your issue. Just so we're all on the same page, I'm assuming [this is the sentence you have issue with](https://docs.ipfs.io/concepts/what-is-ipfs/#decentralization):

> In 2017, Turkey blocked Wikipedia and Spain blocked access to sites related to the Catalonian independence movement.

Correct?

**Comment by felizycontento** [comment]
Right, that is.

Thanks for your answer.

Spain is one of the most democratic countries in Europe. Not only does it guarantee the right to claim the independence of any of its regions, but it also allows political parties that pursue it, to come to power both in these regions (as happened in Catalonia) and in the central state. You can check this is forbidden in many other European countries, like Germany, i.e.

Of course, it also demands that the means to achieve its goals, should be those democratically agreed upon by its citizens, and it pursues any means that involves violence.

**Comment by johnnymatthews** [comment]
That's fair. It's important that the examples we have accurately reflect past events. That being said, the IPFS [gateway ended up being blocked](https://www.reddit.com/r/ipfs/comments/728tt4/note_ipfs_gateway_blocked_in_spain/), so any censorship-resistance IPFS provided was proved moot since folks couldn't access the gateway in the first place.

I'm inclined to **remove this as an example**, since it doesn't really showcase the ability to evade censorship. It's also a fairly politically charged topic. Technical documentation should avoid politics where possible..
