### ISSUE TITLE
Encourage readers to customize their version of the multi-page website.

### ISSUE THREAD

**Issue by adrapper** [ipfs/ipfs-docs#620]
Sorry brain having trouble here... 

If each person going through this tutorial creates exactly the same files. will not the CID generated be exactly the same and therefore the page being display will not be my page but one that the very first person created?

Or am I misunderstanding the way that IPFS deals with duplicates/

When I ran through this tutorial I added a name to the page as in <p>altered by Andrew Drapper</p>, therefore, generating a unique CID to overcome this issue. 

Should the sample code be modified to encourage people to add their own name or nom de plume so that they too generate a unique CID?

**Comment by bertrandfalguiere** [comment]
Or add a random number in the page?

**Comment by johnnymatthews** [comment]
Nope, you're completely correct @adrapper. If I create a `.txt` file with the contents `hello world`, then IPFS gives me the CID `QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o`. But if I edit that file and add an exclamation point `!` to the end of `hello world`, I get the CID `QmeV1kwh3333bsnT6YRfdCRrSgUPngKmAhhTa4RrqYPbKT`.

So in that sense, if everyone following the tutorial just copies and pastes in the code examples without changing _anything_, then everyone will get the same CIDs. If you were to add in an extra space however, or even use tabs instead of spaces, then the CIDs will be different.

Having each reader add something new to their website is probably a good idea! Maybe each reader could add a new _random planet fact_ to the array of facts?

**Comment by adrapper** [comment]
And if they have exactly the same CID, does that mean that it is not really their page that they are viewing, but an earlier creation of that page?

**Comment by johnnymatthews** [comment]
In a sense, yes. As @bertrandfalguiere suggested, if you want to ensure you are retrieving _your_ file, you should customize it in some way.
