### ISSUE TITLE
Add IPFS repo guide

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#669]
As part of the larger ipfs.io rework tracked in https://github.com/orgs/ipfs/projects/11, we'd like to create a page on the docs that lists the "most important" or most frequently relevant IPFS project repos, including information on when they might be relevant. This would be linked to from the main ipfs.io nav menu in response to frequent requests for such in internal and external user testing.

First round of this could be super simple; later, it might be worth spending the time on something that's more useful in terms of being sortable and filterable.

I believe @autonome was starting on this at some point, but unsure about the current status of that work.

**Comment by autonome** [comment]
Le draft: https://hackmd.io/CAVErTC2TvWvYw2dcZigYg

Needs a fill-in-the-gaps and correct-stuff-i-made-up pass by the artists formerly known as Core Implementations.

**Comment by johnnymatthews** [comment]
This is a good idea. I've created the `feat/ipfs-repo-guide` branch, #670 is the draft PR.d

**Comment by jessicaschilling** [comment]
@johnnymatthews I'm ill-equipped to know which repos will fill in the holes in @autonome's outline, but I'm happy to proofread, check links, etc if you or John are able to fit this into your task lists. Let me know what I can do.

**Comment by johnnymatthews** [comment]
Might be able to squeeze this into next weeks milestone. How urgent is this? I threw the `P1` tag on there just arbitrarily.

**Comment by jessicaschilling** [comment]
Sometime before the end of March, if that works?

**Comment by jessicaschilling** [comment]
Update: I took a pass at this in https://github.com/ipfs/ipfs-docs/pull/806. @autonome @johnnymatthews can you please have a look?

**Comment by kvutien** [comment]
I've followed the link and the branch. Beautiful work. IMHO we still need a guide for beginners. Such a guide would be incredibly helpful for people like me who are still learning. 

Currently the repo is more or less flat and all topics are at the same level. A beginner has no clue what concepts have to be learned first. If we take [this one](https://github.com/ipfs/ipfs-docs/tree/main/docs), would it be possible to number the directories to guide the progression? and reorganise the contents of the directories so that each one contains only text for a given level of knowledge?

Awesome project, IPFS.

**Comment by jessicaschilling** [comment]
Hi @kvutien - thanks for the feedback! We can definitely explore some way of adding a more sequential path through the docs overall, or perhaps an indicator of complexity level of a particular article.

In the meantime, you might find useful the concept guides marked "IPFS 101" in the navigation on https://docs.ipfs.io/concepts/ - or the content at https://dweb-primer.ipfs.io/.

**Comment by kvutien** [comment]
Thanks a lot Jessica. Yes, I appreciated a lot the videos and the Primer. However, the 101 is too short and too cryptic for a beginner. Actually I filed an issue for that. But never mind, the Primer, the tutorials of ProtoSchools and the explanation of IPLD made my day.

BTW, allow me some reading comments:
* [README.md#history-of-ipfs](https://github.com/ipfs/ipfs-docs/blob/main/docs/project/README.md#history-of-ipfs): 404
* [... exploring our research repo on GitHub](https://github.com/ipfs/research) redirects to https://github.com/ipfs-inactive which is a bit confusing (but maybe it's an error in the redirection?)
* [... Learn more about the IPFS-related projects](https://github.com/ipfs/ipfs-docs/blob/main/project/related-projects): 404
* [... by contributing to IPFS](https://github.com/ipfs/ipfs-docs/blob/main/project/contribute): 404

Thanks for the awesome good work, otherwise.

**Comment by jessicaschilling** [comment]
@kvutien - you uncovered a larger issue with relative paths not working correctly for folks viewing directly in GitHub (as opposed to on docs.ipfs.io). This will be fixed in https://github.com/ipfs/ipfs-docs/pull/812!

**Comment by kvutien** [comment]
Cool. Yes `docs.ipfs.io` is awesome, starting from the videos in "Concepts". Also the ProtoSchool.

What would be the probability that a beginner like me would start reading from the Github repo, as compared to `docs.ipfs.io`? Do you have an idea? As far as I'm concerned, I started with Github because it's THE reflex of all coders.

My humble opinion, now that I've explored the Github repo, the ProtoSchool and `docs.ipfs.io`, is that ProtoSchool makes it easiest for a beginner to start, then the Github. Now that I know more, I followed your advise to check `docs.ipfs.io`. I could enjoy the videos that comfort my understanding because of earlier knowledge I gained from ProtoSchool..

**Comment by jessicaschilling** [comment]
Thanks for the feedback @kvutien! We don't have access to GitHub traffic data, but you raise a good point. Thanks for the nudge to update all those relative paths — will make the experience significantly better for folks reading directly on GitHub.
