### ISSUE TITLE
Remove broken image link.

### ISSUE THREAD

**Issue by mitchallen** [ipfs/ipfs-docs#695]
The link to the **moon-logo.png** file in this doc is broken:

https://docs.ipfs.io/how-to/websites-on-ipfs/multipage-website/#add-files-to-ipfs

This link:

https://docs.ipfs.io/how-to/websites-on-ipfs/multipage-website/images/multipage-website/moon-logo.png

Returns this in the browser (tested on Chrome on MacOS):

`ipfs resolve -r /ipns/docs.ipfs.io/how-to/websites-on-ipfs/multipage-website/images/multipage-website/moon-logo.png: no link named "images" under bafybeieg3hiohb5qrfjfexjzjm7msoa4mzv5cb3pftvkebllq5j42m5see`

**Comment by johnnymatthews** [comment]
Ah, I see what's happened. That image link is a relative link from an old CID of the docs site. It's probably easier if we just have the user download the image by right-clicking on the image itself, rather than linking off it on another tab.

## Tasks

- [ ] Remove link from `Finally, download this image and save it in the folder as moon-logo.png:`
- [ ] Instruct the user to just download the image by right-clicking on the image below the instruction.
