### ISSUE TITLE
go-ipfs 0.8.0 isn't documented

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-docs#716]
https://docs.ipfs.io/recent-releases/

**Comment by johnnymatthews** [comment]
Issue #480 was created to discuss the relevancy of the Recent Releases section. The main motivation for creating this section was to showcase the release of Go-IPFS 0.5. Since the rest of the releases have pretty much just copied the `readme.md` from the [Release page](https://github.com/ipfs/go-ipfs/releases), it makes sense to just delete this section and add redirects to the relevant readme files in the releases page.

**Comment by johnnymatthews** [comment]
The recent releases section was moved. https://docs.ipfs.io/install/recent-releases/

Closing this issue.
