### ISSUE TITLE
Explain the variable costs associated with buying a domain.

### ISSUE THREAD

**Issue by fugo** [ipfs/ipfs-docs#730]
You should update the prices - ETH domain cost 0,002/year that's about 5$ but the gas fee is 0,04.... right now over 90$! 
Ether is not longer useful for me. 
Hope for Cardano or Algo.

**Comment by johnnymatthews** [comment]
That's a good point. ETH prices are constantly changing, and gas fees fluctuate a lot too. Instead of pointing out how much the domain will likely cost, we should say something like:

> The cost of your domain depends on a few things:
>
> - Which domain you want to purchase.
> - The current price of ETH.
> - The gas fees associated with your transaction.
> - How long you want the domain for.

## Tasks

- [ ] Add the above call out, or something similar, to the [**Before we get started** section of **Link a domain**](https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/#ethereum-naming-service-ens).

**Comment by rshmhrj** [comment]
Hi @johnnymatthews, I'm looking to help out!  Please assign this issue to me.

**Comment by johnnymatthews** [comment]
@rshmhrj I've assigned it to you! Thanks for jumping on this one :)

**Comment by johnnymatthews** [comment]
Merged into `staging`. Thanks for tackling this one @rshmhrj!
