### ISSUE TITLE
Potentially broken _standards_ link.

### ISSUE THREAD

**Issue by mmdalref** [ipfs/ipfs-docs#774]
Hello everyone..
the link to Standards is not working 
i will baste the link below
the error massage is "410 Gone" 
if the link has changed please help me with the new link..
thanks in advance.. 
the link https://ipfs.io/ipfs/bafykbzacedpku3duvucdb3nfbfrlirxqjeas4sld4phi2qti6tfrwxadnr4fa/standards/IEC

**Comment by johnnymatthews** [comment]
Which page did you find this link on @mmdalref?

**Comment by johnnymatthews** [comment]
If the link came from YouTube then there isn't much we can do to fix it. We can only control links from within IPFS Docs. Do you have a link to the YouTube video? We might be able to reach out to the creator and get them to update their link. Otherwise, there's not much we can do. I'm gonna close this issue for now.
