### ISSUE TITLE
Lack of `ipfs` command with `.AppImage` releases causes issues with tutorial and guides that rely on native `ipfs` commands.

### ISSUE THREAD

**Issue by Elmit2015** [ipfs/ipfs-docs#841]
I use ipfs-desktop-0.16.1-linux-x86_64.AppImage on Ubuntu 20.10

It works fine, but I need:

1. I want to use IPNS, so that I can update files. However, the instructions (http://docs.ipfs.io.ipns.localhost:8080/concepts/ipns/#example-ipns-setup-with-cli) Example IPNS setup does not work:
Command 'ipfs'  not found
I tried to find the path for it but failed.

2. I need to move the files to another drive. I have prepared a spare 4 TB external drive for that. 

Thanks for your help!

**Comment by johnnymatthews** [comment]
The problem here is that the IPFS Desktop `.AppImage` doesn't install an IPFS daemon, or even add `ipfs` to your system's `$PATH`. Everything to do with IPFS runs, self-contained, within the `.AppImage` itself.

To get around this, I'm pretty sure you can replace every `ipfs ...` command with `./ipfs-desktop-0.16.1-linux-x86_64.AppImage ...`. So something like:

```shell
./ipfs-desktop-0.16.1-linux-x86_64.AppImage daemon
```

However, I'm not sure if the above command will just spawn another IPFS Desktop instance. I'm spinning up a Ubuntu 20.10 VM as I type this to test this.

In the meantime, you can [install the IPFS CLI using these instructions](https://docs.ipfs.io/install/command-line/#linux).

**Comment by Elmit2015** [comment]
Thanks that worked!
