### ISSUE TITLE
What keeps the last copy of a doc from disappearing?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [ipfs/ipfs-docs#844]
Would love to see everyone's first question answered at the top.  Which is, **what's to keep the last copy of any given document from disappearing?**

Apologies if this is in the docs somewhere...

**Comment by bertrandfalguiere** [comment]
Nothing does. Someone, somewhere, has to have it either because they pinned it or have it in their cache. Either because they are interessed in the data or because they were paid for pinning it. 

General questions should be asked on discuss.ipfs.io . Please ask the question there if you need more details.

**Comment by johnnymatthews** [comment]
[This might help out a bit](https://docs.ipfs.io/concepts/persistence/#persistence-versus-permanence). Gonna close this issue for now. Feel free to continue to comment in here if you still have questions though.

**Comment by michaelkarlcoleman** [comment]
Got it.  Thanks--I thought I was missing something.

**Comment by johnnymatthews** [comment]
No problem. It may be that we need to add in more _key words_ into that page, so that it shows up more prominently in the search results.
