### ISSUE TITLE
CLI install directions automatically reference the latest version

### ISSUE THREAD

**Issue by BigLep** [ipfs/ipfs-docs#905]
**Done criteria:** URLs like https://docs.ipfs.io/install/command-line/#official-distributions automatically reference the latest go-ipfs release.  

**Why important:** saves time for go-ipfs Steward doing a release and ensure users know/use the latest version.

**Customer:** dev team and end users

**Notes:** 
- The 0.10 case where we did this manually: https://github.com/ipfs/ipfs-docs/pull/904

**Comment by ElPaisano** [comment]
Triaging this: 

I see that https://docs.ipfs.tech/install/command-line/#install-official-binary-distributions has replaced https://docs.ipfs.io/install/command-line/#official-distributions (this whole page was overhauled by devrel and docs a few months back). The updated section links to https://dist.ipfs.tech/#kubo, which is automatically updated (by another team) with the latest distros. Based on the doc drift since this issue was opened, and linking out to another site that already does this, I'm going to close this. Please comment and / or reopen if the team feels this is was incorrectly closed. Thank you
