### ISSUE TITLE
NAT configuration

### ISSUE THREAD

**Issue by thedarkknight197** [ipfs/ipfs-docs#939]
Hello I have an ec2 on AWS, I have created an IPFS server private because I need a private ipfs node.
If I connect to my aws shell and use curl to add a new file with 
`curl -X POST 127.0.0.1:5001/api/v0/add -F "file=@text.txt"`

it work, but if I do the same from my client don't.
I recive this message: curl: (7) Failed to connect to XX.XXX.XXX.XXX port 5001: Connection refused
I have open the 5001 port on firewall also on AWS. What I need to do?

**Comment by aschmahmann** [comment]
@thedarkknight197 questions like this are best asked on discuss.ipfs.io so that they can be more easily discovered (closed GitHub issues aren't great for that).

Here's a brief explanation, but if you have more questions feel free to ask there:

Your API port is exposed in your config file as `/ip4/127.0.0.1/tcp/5001` (https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addressesapi) which means that it's only listening on the local interface not whatever is exposed to the world. If you'd like you can change that to `0.0.0.0` or something else.

**However**, doing so will mean that anyone in the world would be able to control your node unless you add some level of protections in front (also given that you're just using HTTP and not HTTPS the data will also not be encrypted as it's sent over the wire between your machine and AWS). So definitely beware before doing this.

**Comment by thedarkknight197** [comment]
> @thedarkknight197 questions like this are best asked on discuss.ipfs.io so that they can be more easily discovered (closed GitHub issues aren't great for that).
> 
> Here's a brief explanation, but if you have more questions feel free to ask there:
> 
> Your API port is exposed in your config file as `/ip4/127.0.0.1/tcp/5001` (https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addressesapi) which means that it's only listening on the local interface not whatever is exposed to the world. If you'd like you can change that to `0.0.0.0` or something else.
> 
> **However**, doing so will mean that anyone in the world would be able to control your node unless you add some level of protections in front (also given that you're just using HTTP and not HTTPS the data will also not be encrypted as it's sent over the wire between your machine and AWS). So definitely beware before doing this.

Thank you or your answer, I will try with 0.0.0.0, it's not a problem because I will have a nodejs middleware that allow access and write data for only user authorized

**Comment by thedarkknight197** [comment]
I open here: https://discuss.ipfs.io/t/help-aws-ipfs-connection-refused/12693
This could be closed
