### ISSUE TITLE
Clean up the PowerShell IPFS install steps.

### ISSUE THREAD

**Issue by GiGiCat101** [ipfs/ipfs-docs#940]
Trying to get ipfs.exeto run on command prompt and or PowerShell on my Win 10 system and followed these instructions to the "T" if you will, only changing what was true to my computer. 

I have included a screen show of PowerShell with the errors so I can get some hel
![PSErrors](https://user-images.githubusercontent.com/94582911/142338753-779030ad-50c2-46be-8d5d-5014c34f89d9.jpg)
p.

**Comment by johnnymatthews** [comment]
Which step did you get to when you encountered that error?

**Comment by GiGiCat101** [comment]
after adding this

Add-Content C:\Users\Johnny\Documents\WindowsPowerShell\profile.ps1
"[System.Environment]::SetEnvironmentVariable('PATH',`$Env:PATH+';;C:\Users\Johnny\Apps\go-ipfs_v0.10.0\go-ipfs')"

and restarting the PowerShell

**Comment by GiGiCat101** [comment]
I changed the paths to navigate in my computer

**Comment by tippi-fifestarr** [comment]
I agree, this problem is connected to the point I was making about how to improve the Documentation for clarity and ease of use for those of us with Lots of Technical Debt. However, I think @GiGiCat101 is asking for help at this step and saying that they also renamed the Johnny to their own system (as Step x) and that they don't know about profile.ps1

My point in the other thread was that this "step" could be broken into smaller steps with curated links to useful information.  Whether or not I am right that this would help people implement your tech is up to the data/you all

**Comment by johnnymatthews** [comment]
Something that I realized recently is that the package you download from dist.ipfs.io contains a script to help install IPFS on MacOS and Linux, but there isn't one for Windows users. To make this whole process easier we could create a PowerShell script that install IPFS properly for Windows users. That script would itself be an amalgamation of everything contained within the Command-line steps you both are referencing.

Would either of you two find such a script useful?

**Comment by johnnymatthews** [comment]
I've created a PR that should address some of this issue. @GiGiCat101 @tippi-fifestarr, can you two both run through these steps to double-check that they work: https://bafybeiclvp5fvyzb2rwxdimjslremr7h5u3hqmmo2eb4f6fwzafc4dtteq.on.fleek.co/install/command-line/#official-distributions

In the meantime, I'll work on creating a PowerShell script for installing IPFS.

**Comment by tippi-fifestarr** [comment]
Thanks, will do and am officially volunteering to help however I can.

Windows Step 1:
Completed no problem

Step 2: Expand-Archive (pasted into command line)
This step failed to create file because it already exists I guess
ExpandArchiveHelper
: Failed to create file
'C:\Users\tippi\Apps\go-ipfs_v0.10.0\go-ipfs\LICENSE'   while expanding the
archive file                        'C:\Users\tippi\go-ipfs_v0.10.0.zip'
contents as the    file
 'C:\Users\tippi\Apps\go-ipfs_v0.10.0\go-ipfs\LICENSE'   already exists.
Use the -Force parameter if you want    to overwrite the existing
directory

Step 3: Navigate to the folder (SUCCESSFUL)
ipfs version 0.10.0

Step 4: no error

Step 5: seems to work (displays a directory and then on repeated input has
no change/ error message)

Step 5.5: notepad $PROFILE (opens an empty notepad file)

Step 6: pasted this into PS and no error message

Step 7: SUCCESS!

Thank you!

**Comment by johnnymatthews** [comment]
Excellent! Thanks for your help in testing @tippi-fifestarr!

**Comment by tippi-fifestarr** [comment]
Keep me posted! My honor 😍 and open-source duty 💪

**Comment by johnnymatthews** [comment]
I've tasted this process on two Windows machines now, @tippi-fifestarr's efforts makes three. So I'm happy to merge this in.

**Comment by tippi-fifestarr** [comment]
Let me know if there are other Windows machines testing or efforts I could make.  One area I am noticing problems on my machine is with loading ipfs links in Brave.  Sometimes it never loads, sometimes it takes ages.  However, if I paste the same link into Firefox (which as far as I can tell, does not have IPFS companion installed into it), it loads via ipfs.io gateway automatically.
