### ISSUE TITLE
Remove unsupported URLs from `:::tip` section.

### ISSUE THREAD

**Issue by da2x** [ipfs/ipfs-docs#988]
https://github.com/ipfs/ipfs-docs/blob/5523597636e895d7868b0e84a9c90a753339502a/docs/how-to/address-ipfs-on-web.md#L47-L57

Brave doesn’t support this, and it’s the only web browser with built-in support for IPFS. Brave only supports the `ipfs://` and `ipns://` schemes, and the `x-ipfs-path` HTTP response headers. The IPFS Companion supports this, but it should probably be removed. This “tip“ section **should be removed from the documentation.**

For instance, this root-path prefix isn’t mention again in the dweb addressing section.
https://github.com/ipfs/ipfs-docs/blob/5523597636e895d7868b0e84a9c90a753339502a/docs/how-to/address-ipfs-on-web.md#L21-L29

**Comment by johnnymatthews** [comment]
This issue is fair. I believe at some point the above example _did_ work, but looks like it doesn't anymore. @da2x your point about Brave not supporting this being a _big thing_ is valid. The fix is pretty trivial here, just rip out that example.

**Comment by lidel** [comment]
> Brave doesn’t support this, [..] 

Brave is not the reference user agent, it is a user agent that makes their own decisions based on external factors :) 
- They do have experimental opt-in redirect support, but it needs more work, including fixing bugs like https://github.com/brave/brave-browser/issues/20567
  - IPFS Stewards&Ecosystem are working with Brave team to get their native support for redirects and DNSLink detection closer to what IPFS Companion does (including DNS lookup instead of reliance on HTTP header etc), but hey have own policy around default behaviors on `https://` 
  - iirc native redirects in Brave have additional constraints because of Brave Shield / limiting impact on `https://` websites:  requests for subresources on `https://` are not redirected, this will happen only if the root document was loaded from `ipfs://` or `ipns://`  (unsure if this shipped, but remember this was a recent fix to fix broken subresources where redirect clashed with rules enforced by Brave Shields)

> this root-path prefix isn’t mention again in the dweb addressing section. 

It is, but maybe not clear enough?
We could make it more explicit here:

```diff
-Through an HTTP gateway, as `http://<gateway host>/<IPFS address>` 
+Through an HTTP gateway, as `https://<gateway host>/ipfs/<cid>` 
```



@johnnymatthews  Commented on (#1003) and suggested tweaking language  to be about user agents and focusing on what Companion does (as the reference user agent that maximizes opportunity for protocol upgrade), and not a specific browser.
