### ISSUE TITLE
Adding a faq: my hash doesn't match the CID

### ISSUE THREAD

**Issue by vmx** [ipfs/ipfs-docs#996]
This came up twice recently (https://github.com/ipld/java-cid/issues/21 and on Slack): "Why does the `sha256sum` hash of the file not match the CID". Both folks were pointed to https://docs.ipfs.io/concepts/hashing/#content-identifiers-are-not-file-hashes.

That page explains in detail what checksums are and how to create them. Though users with this question know this already. Only the last paragraph says:

> To understand what the hash contained in the CID is, we must understand how IPFS stores files. IPFS uses a [directed acyclic graph (DAG)](https://docs.ipfs.io/concepts/merkle-dag/) to keep track of all the data stored in IPFS. A CID identifies one specific node in this graph. This identifier is the result of hashing the node's contents using a cryptographic hash function like SHA256.

That contains a lot of concepts and isn't easy to understand if you're new to the IPFS world. It's not really a "quick" answer. What I propose is having a short answer, then then links to more reading material (like the link to DAG above). if you want to know all the details. The short answer could be something along the lines of: When a file is added to IPFS, it's split into smaller pieces. Each of those pieces is hashed individually, which then results in an overall different hash. For more details…".

**Comment by johnnymatthews** [comment]
This is a fair issue, and a good suggestion. Would you be able to make a PR @vmx? I marked this as a P2, but we don't have any writers to deal with this right now.

**Comment by Annamarie2019** [comment]
I'll take this one.

**Comment by vmx** [comment]
@Annamarie2019 thank you! I haven't found the time yet, so it's great if you are picking it up.

**Comment by Annamarie2019** [comment]
Answered in PR #1017

**Comment by Annamarie2019** [comment]
Hi Volker, I'm addressing this issue by updating the [hashing article](https://docs.ipfs.io/concepts/hashing/#content-identifiers-are-not-file-hashes) and wanted your option. I don't want to be too hasty, since I'm new, but it seems to me that in the section [Content Identifiers are not Hash Files](https://docs.ipfs.io/concepts/hashing/#content-identifiers-are-not-file-hashes) is not useful until the last paragraph. It seems to be telling people the step-by-step of how something does NOT work. I'm not sure we want to be in the business of documenting things that do NOT work. I'm inclined to lead with the last paragraph and just put a one-sentence summary of file verification doesn't work. Is there a need for that info? You opinion? To me, it just adds cognitive load.

**Comment by vmx** [comment]
@Annamarie2019: To answer your question: I would keep it as it currently is. The current hashing article describes that "Content identifiers are not file hashes" well.

To not answer your question: It doesn't answer the question "Why doesn't the SHA match the CID", but it also doesn't try to. I still think that questions belongs to the FAQ section, as it really is frequently asked, especially by new users that don't have the full background and probably also don't care at the point in time when they hit this issue.

**Comment by Annamarie2019** [comment]
These FAQ.md was inadvertantly pulled into another PR. You can double-check the full request was met on:
(Getting Started)[https://docs.ipfs.io/concepts/faq/#getting-started]. See Why doesn't my SHA hash match my CID?

**Comment by Annamarie2019** [comment]
PR #1053

**Comment by johnnymatthews** [comment]
https://github.com/ipfs/ipfs-docs/pull/1053 has been merged. Can we close this now  @Annamarie2019
